name: Publish Devcontainer Feature

on:
  push:
    branches:
      - main
    paths:
      - 'src/aider-installer/**'

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          oci-registry: "ghcr.io"
          features-namespace: "${{ github.repository_owner }}/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
